### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by darkdarcool** [darkdarcool/ConsoleAssister#1]
This is a note to myself to maybe make a typescript version? I know that typescript is not meant for this, but eh?

**Comment by darkdarcool** [comment]
@RayhanADev, is there a way to make a typescript version of this? Like a special installation for it?

**Comment by RayhanADev** [comment]
Hiya!

Wait what do you mean, like transpile this code over to Typescript because that's not impossible.

**Comment by darkdarcool** [comment]
no, well, it is possible to make this typescript with a little tinkering, but what I meant was like to allow someone to install a typescript version of this

**Comment by darkdarcool** [comment]
but typescript requires types, if you make a new typescript repl and put this code in it:
```
import * from 'consoleassister'
it gives me errors
```

**Comment by darkdarcool** [comment]
lol just makes a types thing @darkdarcool. Look it up on their site.(i know i'm being mean to myself, get over it)
